# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-06 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import utility_manager.jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('job_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('API', 'API'), ('Other', 'Other')], max_length=40, null=True)),
                ('command', models.TextField()),
                ('status', models.CharField(blank=True, max_length=40)),
                ('log', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('params', utility_manager.jsonfield.fields.JSONField(blank=True, default={})),
                ('queue', models.CharField(default='web', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
