# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-15 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmanager',
            name='mode',
            field=models.CharField(choices=[('foreground', 'foreground'), ('background', 'background')], max_length=30, null=True),
        ),
    ]
