# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-15 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_manager', '0002_jobmanager_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmanager',
            name='handler',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
