# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-23 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_manager', '0004_auto_20171121_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmanager',
            name='job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
